name: Generate Snake Animation

on:
  # Triggers the workflow on push or every 6 hours to update the snake animation
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: javatcoding1
          output: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake_animation
          path: dist/snake.svg

      - name: Deploy Snake Animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
